# Generated by Django 2.1.5 on 2020-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work',
            field=models.CharField(choices=[['Freelance', 'Freelance'], ['Architecture', 'Architecture'], ['Photography', 'Photography'], ['Design', 'Design']], default='Architecture', max_length=20),
        ),
    ]
